### ISSUE TITLE
Update Rubygems

### ISSUE THREAD

**Issue by thelollies** [rbCAS/casino-activerecord_authenticator#18]
The gemspec in this repository allows for ActiveRecord allows for Activrecord 4.1 but the rubygems version restricts it to  ~> 3.2.12. 

EDIT: It turns out I can't use ActiveRecord 4.2 with the gemspec in this repository.

**Comment by pencil** [comment]
Should be fixed once #17 is merged. Didn't have time to look into this yet but will do so soon.
